version: "3.0"

services:
  hub:
    image: selenium/hub
    ports:
    - "4444"
    networks:
      testsuit: {}

  firefoxnode:
    image: selenium/node-firefox
    links:
      - hub
    networks:
      testsuit: {}
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444     

  chromenode:
    image: selenium/node-chrome
    links:
      - hub
    networks:
      testsuit: {}   
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
  
  apr18:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      testsuit: {}   
    depends_on:
      - hub
      - chromenode
      - firefoxnode
      
networks:
  testsuit:
    driver: bridge

