version: "3.0"
services:
  hub:
    image: selenium/hub
    ports:
    - "4444:4444"
  firefoxnode:
    image: selenium/node-firefox
    links:
      - hub
  chromenode:
    image: selenium/node-chrome
    links:
      - hub
  apr18:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        - PROJECT_PATH=$PROJECT_PATH
    volumes:
      - {WORKSPACE}/output:$PROJECT_PATH/output
    depends_on:
      - hub
      - chromenode
      - firefoxnode

