FROM python:3.6

LABEL maintainer "rus4ca@gmail.com"

ARG PROJECT_PATH=/tmp/app
VOLUME $PROJECT_PATH
WORKDIR $PROJECT_PATH

# We need wget to set up the PPA and xvfb to have a virtual screen and unzip to install the Chromedriver
RUN yum install -y \
    wget \
    xvfb \
    unzip

# Set up the Chrome PPA
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list

# Update the package list and install chrome
RUN yum -y update
RUN yum install -y google-chrome-stable

# Set up Chromedriver Environment variables
ENV CHROMEDRIVER_VERSION 2.19
ENV CHROMEDRIVER_DIR /chromedriver
RUN mkdir $CHROMEDRIVER_DIR

# Download and install Chromedriver
RUN wget -q --continue -P $CHROMEDRIVER_DIR "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
RUN unzip $CHROMEDRIVER_DIR/chromedriver* -d $CHROMEDRIVER_DIR

# Put Chromedriver into the PATH
ENV PATH $CHROMEDRIVER_DIR:$PATH

# set display port and dbus env to avoid hanging
ENV DISPLAY=:99
ENV DBUS_SESSION_BUS_ADDRESS=/dev/null

COPY requirements.txt requirements.txt

RUN python -m venv /tmp/venv && \
	. /tmp/venv/bin/activate && \
	pip install -r requirements.txt
