version: "3"
services:
  hub:
    image: selenium/hub
    ports:
    - "4444:4444"
  firefox:
    image: selenium/node-firefox
    links:
      - hub
  chrome:
    image: selenium/node-chrome
    links:
      - hub
  apr18:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        - PROJECT_PATH=$PROJECT_PATH
      volumes:
        - .:$PROJECT_PATH
    depends_on:
      - hub
      - chrome
      - firefox

