version: "3.0"
volumes:
  output:
services:
  hub:
    image: selenium/hub
    ports:
    - "4444:4444"
  firefoxnode:
    image: selenium/node-firefox
    links:
      - hub
  chromenode:
    image: selenium/node-chrome
    links:
      - hub
  apr18:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - hub
      - chromenode
      - firefoxnode
    volumes:
      - type: volume
        source: {WORKSPACE}/output
        target: /output
